
# Load Homebrew config script
source $HOME/.brewconfig.zsh
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias a='./a.out'
alias f='find . -name'
alias g='grep'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log'
alias gp='git push'
alias gs='git status'
alias m='make'
alias mc='make clean'
alias mf='make fclean'
alias mr='make re'
alias mb='make bonus'
alias r='rm -i'
alias t='tmux'
alias u='cd ..'
alias vs='vi ~/.vimrc'
alias zs='vi ~/.zshrc'
alias bs='vi ~/.bashrc'
