[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''


[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
	\   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
	\   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'

